name: Latest pipeline

on:
  push:
    branches:
      - main

jobs:
  oldpipeline:
    runs-on: ubuntu-Latest
    steps:
      - name: print something
        runs: echo "data pipeline"
      - name: end something
        runs: |
          echo "middle pipeline"
          mkdir sample
          echo "end pipeline"